import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";

const playFair = Playfair({
  variable: "--font-playfair-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pages & Papilles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playFair.variable} antialiased`}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
